var sprites={};
var saveKey='alien-invasion-run',upgradeKey='alien-invasion-upgrades';
var upgrades;try{upgrades=JSON.parse(localStorage.getItem(upgradeKey)||'{"rapid":0,"power":0,"armor":0}')}catch(e){upgrades={rapid:0,power:0,armor:0}}
function saveRun(x){try{localStorage.setItem(saveKey,JSON.stringify(x))}catch(e){}}
function clearRun(){try{localStorage.removeItem(saveKey)}catch(e){}}
function title(t,s,go){Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;go()}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 34px Arial';c.fillText(t,160,190);c.font='14px Arial';c.fillText(s,160,225);c.fillText('Arrows / A-D / controller: move',160,260);c.fillText('Space / '+(Game.glyph||'A')+' fire  •  P pause',160,282);c.textAlign='left'}})}
function startGame(){Game.setBoard(0,new Stars());var r=localStorage.getItem(saveKey);title('ALIEN INVASION',r?'Press fire to resume':'Press fire to launch',function(){play(!!r)})}
function play(resume){var r=resume?JSON.parse(localStorage.getItem(saveKey)||'{}'):{};Game.points=r.score||0;Game.combo=r.combo||1;var b=new Board();b.player=b.add(new Player(r.x));b.add(new Wave(r.time||0));Game.setBoard(1,b);Game.setBoard(2,new HUD());Game.setBoard(3,null);Game.setBoard(4,new Touch())}
function finish(t,s){clearRun();title(t,s,function(){play(false)})}
function Stars(){this.s=[];for(var i=0;i<100;i++)this.s.push([Math.random()*320,Math.random()*480,20+Math.random()*80]);this.step=function(d){this.s.forEach(function(s){s[1]=(s[1]+s[2]*d)%480})};this.draw=function(c){c.fillStyle='#03050d';c.fillRect(0,0,320,480);c.fillStyle='#fff';this.s.forEach(function(s){c.fillRect(s[0],s[1],1,1)})}}
function Board(){this.objects=[];this.add=function(x){x.board=this;this.objects.push(x);return x};this.step=function(d){for(var i=0;i<this.objects.length;i++)this.objects[i].step(d);this.objects=this.objects.filter(function(x){return !x.dead})};this.draw=function(c){this.objects.forEach(function(x){x.draw(c)})};this.hit=function(a,type){for(var i=0;i<this.objects.length;i++){var o=this.objects[i];if(o!==a&&o.type===type&&a.x<o.x+o.w&&a.x+a.w>o.x&&a.y<o.y+o.h&&a.y+a.h>o.y)return o}return null}}
function Player(x){this.type='player';this.x=x==null?142:x;this.y=425;this.w=37;this.h=42;this.hp=1+(upgrades.armor||0);this.cool=0;this.step=function(d){this.x+=((Game.keys.right?1:0)-(Game.keys.left?1:0))*230*d;this.x=Math.max(0,Math.min(283,this.x));this.cool-=d;if(Game.keys.fire&&this.cool<=0){this.cool=Math.max(.08,.25-(upgrades.rapid||0)*.04);this.fire(this.x+18);Game.keys.fire=false}var p=this.board.hit(this,'power');if(p){if(p.kind==='rapid')upgrades.rapid++;if(p.kind==='spread')upgrades.power++;if(p.kind==='shield')this.hp++;try{localStorage.setItem(upgradeKey,JSON.stringify(upgrades))}catch(e){}p.dead=true}};this.fire=function(x){this.board.add(new Bullet(x,this.y));if((upgrades.power||0)>1)this.board.add(new Bullet(x-12,this.y));if((upgrades.power||0)>2)this.board.add(new Bullet(x+12,this.y))};this.damage=function(){if(--this.hp<=0)finish('SHIP LOST','Final score: '+Game.points)};this.draw=function(c){c.fillStyle='#55d8ff';c.beginPath();c.moveTo(this.x+18,this.y);c.lineTo(this.x,this.y+30);c.lineTo(this.x+37,this.y+30);c.fill()}}
function Bullet(x,y){this.type='bullet';this.x=x;this.y=y;this.w=4;this.h=10;this.step=function(d){this.y-=450*d;var e=this.board.hit(this,'enemy')||this.board.hit(this,'boss');if(e){e.hp-=10;this.dead=true;if(e.hp<=0){e.dead=true;Game.points+=(e.value||100)*(Game.combo||1);Game.combo=Math.min(9,(Game.combo||1)+1);if(Math.random()<.2)this.board.add(new Power(e.x,e.y))}}if(this.y<0)this.dead=true};this.draw=function(c){c.fillStyle='#ffef63';c.fillRect(this.x,this.y,this.w,this.h)}}
function Enemy(x,boss){this.type=boss?'boss':'enemy';this.x=x;this.y=boss?35:-30;this.w=boss?120:36;this.h=boss?55:35;this.hp=boss?700:20;this.value=boss?5000:100;this.t=0;this.step=function(d){this.t+=d;if(!boss)this.y+=55*d;this.x+=Math.sin(this.t*(boss?0.8:2))*40*d;if(Math.random()<d*.3)this.board.add(new Shot(this.x+this.w/2,this.y+this.h));var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>500)this.dead=true};this.draw=function(c){c.fillStyle=boss?'#d32f4f':'#a65cff';c.fillRect(this.x,this.y,this.w,this.h);if(boss){c.fillStyle='#ff8a9a';c.fillRect(35,10,250*(this.hp/700),8)}}}
function Shot(x,y){this.type='shot';this.x=x;this.y=y;this.w=5;this.h=12;this.step=function(d){this.y+=220*d;var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle='#ff466e';c.fillRect(this.x,this.y,this.w,this.h)}}
function Power(x,y){this.type='power';this.kind=['rapid','spread','shield'][Math.floor(Math.random()*3)];this.x=x;this.y=y;this.w=20;this.h=20;this.step=function(d){this.y+=50*d;if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle=this.kind==='rapid'?'#ffef63':this.kind==='spread'?'#fa6cff':'#5df';c.beginPath();c.arc(this.x+10,this.y+10,10,0,Math.PI*2);c.fill()}}
function Wave(t){this.t=t;this.spawnedBoss=false;this.step=function(d){this.t+=d;if(!this.spawnedBoss&&this.t>25&&!this.board.objects.some(function(o){return o.type==='enemy'})){this.board.add(new Enemy(100,true));this.spawnedBoss=true}else if(!this.spawnedBoss&&Math.random()<d*.9)this.board.add(new Enemy(Math.random()*280,false));if(Game.keys.pause){Game.keys.pause=false;saveRun({score:Game.points,combo:Game.combo,x:this.board.player.x,time:this.t});title('PAUSED','Progress saved • press fire',function(){play(true)})}};this.draw=function(){}}
function HUD(){this.step=function(){};this.draw=function(c){c.fillStyle='#fff';c.font='bold 14px Arial';c.fillText('SCORE '+String(Game.points||0).padStart(7,'0'),8,20);c.fillText('x'+(Game.combo||1),250,20)}}
function Touch(){this.step=function(){};this.draw=function(c){c.fillStyle='#fff6';c.fillRect(8,438,45,34);c.fillRect(60,438,45,34);c.fillRect(260,438,52,34);c.fillStyle='#fff';c.font='bold 20px Arial';c.fillText('◀',20,462);c.fillText('▶',72,462);c.fillText(Game.glyph||'A',275,461)}}
window.addEventListener('load',function(){Game.initialize('game',sprites,startGame)});
