var meta;try{meta=JSON.parse(localStorage.getItem('alien-invasion-meta')||'{"credits":0,"maxHp":0,"weapon":0,"cooldown":0}')}catch(e){meta={credits:0,maxHp:0,weapon:0,cooldown:0}}
function metaSave(){try{localStorage.setItem('alien-invasion-meta',JSON.stringify(meta))}catch(e){}}function runRead(){try{return JSON.parse(localStorage.getItem('alien-invasion-run')||'null')}catch(e){return null}}function runSave(v){try{localStorage.setItem('alien-invasion-run',JSON.stringify(v))}catch(e){}}function runClear(){try{localStorage.removeItem('alien-invasion-run')}catch(e){}}
function screen(title,sub,action){Game.setBoard(3,{step:function(){if(Game.keys.fire&&!this.lock){this.lock=true;Game.keys.fire=false;action()}if(!Game.keys.fire)this.lock=false},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 30px Arial';c.fillText(title,160,175);c.font='14px Arial';c.fillText(sub,160,210);c.fillText('Move: arrows/A-D   Fire: '+(Game.gamepad.fire||'A')+'/Space',160,245);c.fillText('Pause: P/Escape  Upgrade: U  Run skills: K',160,268);c.textAlign='left'}})}
function start(){Game.setBoard(0,new Stars());var save=runRead();screen('ALIEN INVASION',save?'Fire to resume  |  U upgrade bay':'Fire to launch  |  U upgrade bay',function(){play(!!save)});Game.setBoard(4,new Touch())}
function upgrades(){Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;start()}if(Game.keys.upgrade){Game.keys.upgrade=false;var cost=2+(meta.maxHp||0);if(meta.credits>=cost){meta.credits-=cost;meta.maxHp++;metaSave()}}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 23px Arial';c.fillText('UPGRADE BAY',160,130);c.font='14px Arial';c.fillText('Credits: '+(meta.credits||0),160,160);c.fillText((Game.gamepad.upgrade||'Y')+' / U: +1 max health (cost '+(2+(meta.maxHp||0))+')',160,195);c.fillText('Fire to return',160,225);c.textAlign='left'}})}
function play(resume){var r=resume?runRead()||{}:{};Game.points=r.score||0;Game.combo=r.combo||1;var b=new Board();b.player=b.add(new Player(r.x,r.hp,r.lives,r.skills));b.wave=b.add(new Wave(r.time||0));Game.setBoard(1,b);Game.setBoard(2,new Hud());Game.setBoard(3,null);Game.paused=false}
function pause(b){if(Game.paused)return;Game.paused=true;var p=b.player;runSave({score:Game.points,combo:Game.combo,x:p.x,hp:p.hp,lives:p.lives,skills:p.skills,time:b.wave.t});Game.keys.pause=false;Game.keys.fire=false;Game.setBoard(3,new PauseMenu(b))}
function finish(title){var credits=Math.floor((Game.points||0)/1000);meta.credits=(meta.credits||0)+credits;metaSave();runClear();screen(title,'Score '+Game.points+'  |  Credits +'+credits,function(){play(false)})}
function Board(){this.objects=[];this.add=function(o){o.board=this;this.objects.push(o);return o};this.step=function(d){for(var i=0;i<this.objects.length;i++)this.objects[i].step(d);this.objects=this.objects.filter(function(o){return !o.dead})};this.draw=function(c){for(var i=0;i<this.objects.length;i++)this.objects[i].draw(c)};this.hit=function(a,t){for(var i=0;i<this.objects.length;i++){var o=this.objects[i];if(o!==a&&o.type===t&&a.x<o.x+o.w&&a.x+a.w>o.x&&a.y<o.y+o.h&&a.y+a.h>o.y)return o}return null}}
function PauseMenu(b){this.lock=true;this.step=function(){if(!Game.keys.fire)this.lock=false;if(Game.keys.fire&&!this.lock){Game.keys.fire=false;Game.paused=false;Game.setBoard(3,null)}};this.draw=function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 32px Arial';c.fillText('PAUSED',160,190);c.font='14px Arial';c.fillText('Press fire / '+(Game.gamepad.fire||'A')+' to resume',160,225);c.textAlign='left'}}
function Stars(){this.a=[];for(var i=0;i<100;i++)this.a.push([Math.random()*320,Math.random()*480,20+Math.random()*80]);this.step=function(d){for(var i=0;i<this.a.length;i++)this.a[i][1]=(this.a[i][1]+this.a[i][2]*d)%480};this.draw=function(c){c.fillStyle='#03050d';c.fillRect(0,0,320,480);c.fillStyle='#fff';for(var i=0;i<this.a.length;i++)c.fillRect(this.a[i][0],this.a[i][1],1,1)}}
function Player(x,hp,lives,skills){this.type='player';this.x=x==null?142:x;this.y=425;this.w=37;this.h=35;this.max=3+(meta.maxHp||0);this.hp=hp==null?this.max:hp;this.lives=lives==null?3:lives;this.skills=skills||{rapid:0,spread:0,shield:0};this.cool=0;this.step=function(d){if(Game.keys.pause){pause(this.board);return}if(Game.keys.skill){Game.keys.skill=false;this.skillMenu();return}this.x+=((Game.keys.right?1:0)-(Game.keys.left?1:0))*230*d;this.x=Math.max(0,Math.min(283,this.x));this.cool-=d;if(Game.keys.fire&&this.cool<=0){this.cool=Math.max(.07,.24-this.skills.rapid*.025-(meta.cooldown||0)*.03);this.fire();Game.keys.fire=false}var p=this.board.hit(this,'power');if(p){if(p.kind==='health')this.hp=Math.min(this.max,p.hp||this.hp+1);else this.skills[p.kind]++;p.dead=true}};this.fire=function(){var n=1+this.skills.spread+(meta.weapon||0);for(var i=0;i<n;i++)this.board.add(new Bullet(this.x+18+(i-(n-1)/2)*12,this.y))};this.damage=function(){if(this.skills.shield){this.skills.shield--;return}this.hp--;if(this.hp<=0){this.lives--;if(this.lives){this.hp=this.max;this.x=142}else finish('SHIP LOST')}};this.skillMenu=function(){var p=this;Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;Game.setBoard(3,null)}if(Game.keys.skill){Game.keys.skill=false;var cost=100*(1+p.skills.rapid+p.skills.spread+p.skills.shield);if(Game.points>=cost){Game.points-=cost;p.skills.rapid++}}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 24px Arial';c.fillText('RUN SKILLS',160,145);c.font='14px Arial';c.fillText('Score: '+Game.points,160,175);c.fillText((Game.gamepad.skill||'X')+' / K: buy rapid fire (cost scales)',160,205);c.fillText('Fire to resume',160,235);c.textAlign='left'}})};this.draw=function(c){c.fillStyle='#55d8ff';c.beginPath();c.moveTo(this.x+18,this.y);c.lineTo(this.x,this.y+30);c.lineTo(this.x+37,this.y+30);c.fill()}}
function Bullet(x,y){this.type='bullet';this.x=x;this.y=y;this.w=4;this.h=10;this.step=function(d){this.y-=450*d;var e=this.board.hit(this,'enemy')||this.board.hit(this,'boss');if(e){e.hp-=10;this.dead=true;if(e.hp<=0){Game.points+=(e.value||100)*(Game.combo||1);Game.combo=Math.min(9,(Game.combo||1)+1);e.dead=true;if(Math.random()<.25)this.board.add(new Power(e.x,e.y))}}if(this.y<0)this.dead=true};this.draw=function(c){c.fillStyle='#ffef63';c.fillRect(this.x,this.y,this.w,this.h)}}
function Enemy(x,boss,wave){this.type=boss?'boss':'enemy';this.boss=!!boss;this.wave=wave||1;this.variant=boss?'boss':['scout','zigzag','tank'][Math.floor(Math.random()*3)];this.x=x;this.y=boss?30:-35;this.w=boss?130:(this.variant==='tank'?46:34);this.h=boss?58:(this.variant==='tank'?42:32);this.max=boss?500+this.wave*180:(this.variant==='tank'?45:12+this.wave*3);this.hp=this.max;this.value=boss?5000*this.wave:100*this.wave;this.t=0;this.reload=.8;this.step=function(d){this.t+=d;var phase=this.hp<this.max*.5;if(this.boss)this.x=95+Math.sin(this.t*(phase?1.6:.8))*(phase?90:65);else{this.y+=(this.variant==='tank'?38:62+this.wave*3)*d;this.x+=Math.sin(this.t*(this.variant==='zigzag'?5:2))*(this.variant==='zigzag'?95:25)*d}this.reload-=d;if(this.reload<=0){this.reload=this.boss?(phase?.28:.62):(this.variant==='tank'?1.1:1.7);this.board.add(new Shot(this.x+this.w/2,this.y+this.h));if(this.boss&&phase){this.board.add(new Shot(this.x+15,this.y+this.h));this.board.add(new Shot(this.x+this.w-15,this.y+this.h))}}var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>500)this.dead=true};this.draw=function(c){c.fillStyle=this.boss?'#d32f4f':this.variant==='tank'?'#e08a32':this.variant==='zigzag'?'#45d6a5':'#a65cff';c.fillRect(this.x,this.y,this.w,this.h);if(this.boss){c.fillStyle='#ff8a9a';c.fillRect(35,10,250*Math.max(0,this.hp/this.max),8);c.fillStyle='#fff';c.font='11px Arial';c.fillText('BOSS '+(this.hp<this.max*.5?'PHASE 2':'PHASE 1'),122,30)}}}
function Shot(x,y){this.type='shot';this.x=x;this.y=y;this.w=5;this.h=12;this.step=function(d){this.y+=220*d;var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle='#ff466e';c.fillRect(this.x,this.y,this.w,this.h)}}
function Power(x,y){this.type='power';this.kind=['health','rapid','spread','shield'][Math.floor(Math.random()*4)];this.x=x;this.y=y;this.w=20;this.h=20;this.step=function(d){this.y+=50*d;if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle=this.kind==='health'?'#5f6':this.kind==='rapid'?'#ffef63':this.kind==='spread'?'#fa6cff':'#5df';c.beginPath();c.arc(this.x+10,this.y+10,10,0,Math.PI*2);c.fill()}}
function Wave(t){this.t=t;this.wave=1;this.phase='enemies';this.spawned=0;this.step=function(d){if(Game.keys.pause){pause(this.board);return}this.t+=d;var b=this.board,enemyAlive=b.objects.some(function(o){return o.type==='enemy'}),bossAlive=b.objects.some(function(o){return o.type==='boss'});if(this.phase==='enemies'&&!enemyAlive&&this.spawned>=5+this.wave*2){this.phase='boss';b.add(new Enemy(95,true,this.wave));return}if(this.phase==='boss'&&!bossAlive){Game.points+=1000*this.wave;this.wave++;this.spawned=0;this.t=0;this.phase='enemies';return}if(this.phase==='enemies'&&this.spawned<5+this.wave*2&&Math.random()<d*(1+.1*this.wave)){b.add(new Enemy(Math.random()*280,false,this.wave));this.spawned++}};this.draw=function(){}}
function Hud(){this.step=function(){};this.draw=function(c){var p=Game.active()&&Game.active().player;c.fillStyle='#fff';c.font='bold 14px Arial';c.fillText('SCORE '+String(Game.points).padStart(7,'0'),8,18);if(p){c.fillStyle='#f66';c.fillText('HP '+p.hp+'/'+p.max+'  LIVES '+p.lives,8,38)}c.fillStyle='#ffd34d';c.fillText('WAVE '+(Game.active()&&Game.active().wave?Game.active().wave.wave:1),220,18)}}
function Touch(){this.step=function(){};this.draw=function(c){c.fillStyle='#fff6';c.fillRect(8,438,45,34);c.fillRect(60,438,45,34);c.fillRect(260,438,52,34);c.fillStyle='#fff';c.font='bold 20px Arial';c.fillText('◀',20,462);c.fillText('▶',72,462);c.fillText(Game.gamepad.fire||'A',275,462)}}
window.addEventListener('load',function(){Game.initialize('game',start)})
