var sprites={};
var SAVE_KEY='alien-invasion-run',META_KEY='alien-invasion-meta',meta;try{meta=JSON.parse(localStorage.getItem(META_KEY)||'{"credits":0,"maxHp":0,"weapon":0,"cooldown":0}')}catch(e){meta={credits:0,maxHp:0,weapon:0,cooldown:0}}
function readSave(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch(e){return null}}function writeSave(v){try{localStorage.setItem(SAVE_KEY,JSON.stringify(v))}catch(e){}}function clearSave(){try{localStorage.removeItem(SAVE_KEY)}catch(e){}}function persistMeta(){try{localStorage.setItem(META_KEY,JSON.stringify(meta))}catch(e){}}
function textScreen(t,s,action){Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;action()}if(Game.keys.u){Game.keys.u=false;upgradeScreen()}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 32px Arial';c.fillText(t,160,170);c.font='14px Arial';c.fillText(s,160,205);c.fillText('Arrows / A-D / controller: move',160,245);c.fillText('Space / '+(Game.glyph||'A')+' fire  -  P pause  -  U upgrades',160,268);c.textAlign='left'}})}
function startGame(){Game.setBoard(0,new Stars());var saved=readSave();textScreen('ALIEN INVASION',saved?'Press fire to resume  -  U: upgrades':'Press fire to launch  -  U: upgrades',function(){play(!!saved)});Game.setBoard(4,new Touch())}
function upgradeScreen(){Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;startGame()}if(Game.keys.u){Game.keys.u=false;var cost=1+(meta.maxHp||0);if(meta.credits>=cost){meta.credits-=cost;meta.maxHp++;persistMeta()}}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 22px Arial';c.fillText('META UPGRADE BAY',160,120);c.font='14px Arial';c.fillText('Credits: '+(meta.credits||0),160,150);c.fillText('U: buy Health +1  -  cost '+(1+(meta.maxHp||0)),160,180);c.fillText('Fire: return',160,215);c.textAlign='left'}})}
function play(resume){var r=resume?readSave()||{}:{};Game.points=r.score||0;Game.combo=r.combo||1;var b=new Board();b.player=b.add(new Player(r.x,r.hp,r.lives,r.skills));b.wave=b.add(new Wave(r.time||0));Game.setBoard(1,b);Game.setBoard(2,new HUD());Game.setBoard(3,null);Game.setBoard(4,new Touch())}
function pauseRun(b){var p=b.player;writeSave({score:Game.points,combo:Game.combo,x:p.x,hp:p.hp,lives:p.lives,skills:p.skills,time:b.wave.t});textScreen('PAUSED','Run saved - press fire to resume',function(){play(true)})}
function finish(t,s){clearSave();meta.credits=(meta.credits||0)+Math.floor((Game.points||0)/1000);persistMeta();textScreen(t,s+'  Credits: '+meta.credits,function(){play(false)})}
function Stars(){this.s=[];for(var i=0;i<100;i++)this.s.push([Math.random()*320,Math.random()*480,20+Math.random()*80]);this.step=function(d){this.s.forEach(function(s){s[1]=(s[1]+s[2]*d)%480})};this.draw=function(c){c.fillStyle='#03050d';c.fillRect(0,0,320,480);c.fillStyle='#fff';this.s.forEach(function(s){c.fillRect(s[0],s[1],1,1)})}}
function Board(){this.objects=[];this.add=function(o){o.board=this;this.objects.push(o);return o};this.step=function(d){for(var i=0;i<this.objects.length;i++)this.objects[i].step(d);this.objects=this.objects.filter(function(o){return !o.dead})};this.draw=function(c){this.objects.forEach(function(o){o.draw(c)})};this.hit=function(a,type){for(var i=0;i<this.objects.length;i++){var o=this.objects[i];if(o!==a&&o.type===type&&a.x<o.x+o.w&&a.x+a.w>o.x&&a.y<o.y+o.h&&a.y+a.h>o.y)return o}return null}}
function Player(x,hp,lives,skills){this.type='player';this.x=x==null?142:x;this.y=425;this.w=37;this.h=42;this.maxHp=3+(meta.maxHp||0);this.hp=hp==null?this.maxHp:hp;this.lives=lives==null?3:lives;this.cool=0;this.skills=skills||{rapid:0,spread:0,shield:0};this.step=function(d){this.x+=((Game.keys.right?1:0)-(Game.keys.left?1:0))*230*d;this.x=Math.max(0,Math.min(283,this.x));this.cool-=d;if(Game.keys.fire&&this.cool<=0){this.cool=Math.max(.07,.24-(meta.cooldown||0)*.03-this.skills.rapid*.025);this.fire(this.x+18);Game.keys.fire=false}var p=this.board.hit(this,'power');if(p){this.apply(p.kind);p.dead=true}if(Game.keys.k){Game.keys.k=false;this.openSkills()}};this.fire=function(x){this.board.add(new Bullet(x,this.y));var spread=this.skills.spread+(meta.weapon||0);if(spread>0)this.board.add(new Bullet(x-12,this.y));if(spread>1)this.board.add(new Bullet(x+12,this.y))};this.apply=function(k){if(k==='health')this.hp=Math.min(this.maxHp,this.hp+1);else if(k==='rapid')this.skills.rapid++;else if(k==='spread')this.skills.spread++;else this.skills.shield++};this.damage=function(){if(this.skills.shield>0){this.skills.shield--;return}this.hp--;if(this.hp<=0){this.lives--;if(this.lives>0){this.hp=this.maxHp;this.x=142}else finish('SHIP LOST','Final score: '+Game.points)}};this.openSkills=function(){var p=this;Game.setBoard(3,{step:function(){if(Game.keys.fire){Game.keys.fire=false;Game.setBoard(3,null)}if(Game.keys.u){Game.keys.u=false;var cost=1+p.skills.rapid+p.skills.spread+p.skills.shield;if(Game.points>=cost*100){Game.points-=cost*100;p.skills.rapid++}}},draw:function(c){c.fillStyle='#fff';c.textAlign='center';c.font='bold 24px Arial';c.fillText('RUN SKILLS',160,145);c.font='14px Arial';c.fillText('Points: '+Game.points,160,175);c.fillText('U: buy Rapid Fire (cost scales)',160,205);c.fillText('Fire: continue',160,235);c.textAlign='left'}})};this.draw=function(c){c.fillStyle='#55d8ff';c.beginPath();c.moveTo(this.x+18,this.y);c.lineTo(this.x,this.y+30);c.lineTo(this.x+37,this.y+30);c.fill()}}
function Bullet(x,y){this.type='bullet';this.x=x;this.y=y;this.w=4;this.h=10;this.step=function(d){this.y-=450*d;var e=this.board.hit(this,'enemy')||this.board.hit(this,'boss');if(e){e.hp-=10;this.dead=true;if(e.hp<=0){e.dead=true;Game.points+=(e.value||100)*(Game.combo||1);Game.combo=Math.min(9,(Game.combo||1)+1);if(Math.random()<.24)this.board.add(new Power(e.x,e.y))}}if(this.y<0)this.dead=true};this.draw=function(c){c.fillStyle='#ffef63';c.fillRect(this.x,this.y,this.w,this.h)}}
function Enemy(x,boss){this.type=boss?'boss':'enemy';this.x=x;this.y=boss?35:-30;this.w=boss?120:36;this.h=boss?55:35;this.hp=boss?700:20;this.value=boss?5000:100;this.t=0;this.step=function(d){this.t+=d;if(!boss)this.y+=55*d;this.x+=Math.sin(this.t*(boss?0.8:2))*40*d;if(Math.random()<d*.3)this.board.add(new Shot(this.x+this.w/2,this.y+this.h));var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>500)this.dead=true};this.draw=function(c){c.fillStyle=boss?'#d32f4f':'#a65cff';c.fillRect(this.x,this.y,this.w,this.h);if(boss){c.fillStyle='#ff8a9a';c.fillRect(35,10,250*(this.hp/700),8)}}}
function Shot(x,y){this.type='shot';this.x=x;this.y=y;this.w=5;this.h=12;this.step=function(d){this.y+=220*d;var p=this.board.hit(this,'player');if(p){p.damage();this.dead=true}if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle='#ff466e';c.fillRect(this.x,this.y,this.w,this.h)}}
function Power(x,y){this.type='power';this.kind=['health','rapid','spread','shield'][Math.floor(Math.random()*4)];this.x=x;this.y=y;this.w=20;this.h=20;this.step=function(d){this.y+=50*d;if(this.y>480)this.dead=true};this.draw=function(c){c.fillStyle=this.kind==='health'?'#5f6':this.kind==='rapid'?'#ffef63':this.kind==='spread'?'#fa6cff':'#5df';c.beginPath();c.arc(this.x+10,this.y+10,10,0,Math.PI*2);c.fill()}}
function Wave(t){this.t=t;this.spawnedBoss=false;this.step=function(d){this.t+=d;if(!this.spawnedBoss&&this.t>25&&!this.board.objects.some(function(o){return o.type==='enemy'})){this.board.add(new Enemy(100,true));this.spawnedBoss=true}else if(!this.spawnedBoss&&Math.random()<d*.9)this.board.add(new Enemy(Math.random()*280,false));if(Game.keys.pause){Game.keys.pause=false;pauseRun(this.board)}};this.draw=function(){}}
function HUD(){this.step=function(){};this.draw=function(c){var p=Game.boards[1]&&Game.boards[1].player;c.fillStyle='#fff';c.font='bold 14px Arial';c.fillText('SCORE '+String(Game.points||0).padStart(7,'0'),8,20);c.fillText('x'+(Game.combo||1),250,20);if(p){c.fillStyle='#f44';c.fillText('HP '+p.hp+'/'+p.maxHp,8,40);c.fillStyle='#ffd34d';c.fillText('LIVES '+p.lives,220,40)}}}
function Touch(){this.step=function(){};this.draw=function(c){c.fillStyle='#fff6';c.fillRect(8,438,45,34);c.fillRect(60,438,45,34);c.fillRect(260,438,52,34);c.fillStyle='#fff';c.font='bold 20px Arial';c.fillText('◀',20,462);c.fillText('▶',72,462);c.fillText(Game.glyph||'A',275,461)}}
window.addEventListener('load',function(){Game.initialize('game',sprites,startGame)});
